// Package generate turns the catalog into the artifacts that make ownership
// metadata load-bearing: CODEOWNERS, alert routing, and the Slack channel map
// (spec §11). Every one is derived, never hand-edited, and verified by
// `landsraad gen --check`.
//
// Each generator is a pure function returning an emit.File. Nothing here
// touches the filesystem; cmd/ writes what these return.
package generate

import (
	"fmt"
	"sort"
	"strings"

	"github.com/landsraadhq/landsraad/internal/catalog"
	"github.com/landsraadhq/landsraad/internal/config"
	"github.com/landsraadhq/landsraad/internal/diag"
	"github.com/landsraadhq/landsraad/internal/emit"
)

// CodeownersPath is where CODEOWNERS is written, relative to the repository
// root. GitHub also accepts .github/CODEOWNERS and docs/CODEOWNERS; the root
// is the one every host reads.
const CodeownersPath = "CODEOWNERS"

// Banner is the header every generated artifact carries. A generated file that
// does not say it is generated gets hand-edited, and the edit is silently
// destroyed on the next run.
func Banner(source string) string {
	return "# Generated by landsraad. Do not edit.\n" +
		"# Source: " + source + ".\n" +
		"# Run `landsraad gen` to regenerate; `landsraad gen --check` fails when this is stale.\n"
}

// CODEOWNERS renders the ownership rules implied by the catalog.
//
// Entries are sorted by path. git evaluates CODEOWNERS last-match-wins, so a
// more specific path must appear after the general one it overrides, and
// lexical order gives that. It also makes the output stable between runs: a
// generated file that reorders itself makes `gen --check` fail at random.
//
// That reasoning covers *nested* paths, where a later line overriding an
// earlier one is the point. Two entities resolving to the **same** path is a
// different case and ruling R50 covers it: last-match-wins there is an
// override nobody expressed, so owners that render identically are deduped
// and owners that differ are an error rather than a silently voided team.
//
// Owners come from the team's members (spec §11 routes owner through
// teams.yaml). config.Team carries no host team handle, so members it is; a
// handle already written with a leading @ is left alone.
func CODEOWNERS(cat *catalog.Catalog, teams *config.Teams, c *diag.Collector) emit.File {
	type entry struct{ path, owners string }
	var entries []entry

	// Ruling R50. CODEOWNERS is keyed on path, but the catalog's uniqueness
	// invariant is (kind, name) and nothing constrains spec.path to be unique.
	// The projection from entities to paths is therefore not injective, and
	// git's last-match-wins makes every line but the last one a no-op — so two
	// differently-owned entities on one path silently strip the first team of
	// the review rights this file exists to grant.
	type claim struct {
		owners string
		by     *catalog.Entity
	}
	claimed := make(map[string]claim)

	for _, e := range cat.Entities() {
		// An entity that describes something outside this repository omits
		// spec.path (spec §5). A CODEOWNERS rule for a path that does not
		// exist is one git silently ignores.
		if e.Spec.Path == "" {
			continue
		}
		team, ok := teams.Get(e.Metadata.Owner)
		if !ok {
			c.Add(diag.Diagnostic{
				Severity: diag.SevError,
				Repo:     e.SourceRepo,
				File:     e.SourcePath,
				Line:     e.NameLine,
				Entity:   e.Metadata.Name,
				Check:    "codeowners-unknown-owner",
				Message: fmt.Sprintf("owner %q of %s is not defined in teams.yaml",
					e.Metadata.Owner, e.Ref()),
				Hint: "every owner must be a team in teams.yaml",
			})
			continue
		}
		owners := handles(team.Members)
		if len(owners) == 0 {
			// A CODEOWNERS line with a path and no owner means "nobody owns
			// this" to git, which silently removes the review requirement the
			// file exists to create.
			c.Add(diag.Diagnostic{
				Severity: diag.SevError,
				Repo:     e.SourceRepo,
				File:     e.SourcePath,
				Line:     e.NameLine,
				Entity:   e.Metadata.Name,
				Check:    "codeowners-no-members",
				Message: fmt.Sprintf("team %q owns %s but lists no members, so CODEOWNERS would leave it unowned",
					team.Name, e.Ref()),
				Hint: fmt.Sprintf("add members to %s in teams.yaml", team.Name),
			})
			continue
		}
		p := ownedPath(e)
		joined := strings.Join(owners, " ")
		if prev, exists := claimed[p]; exists {
			if prev.owners == joined {
				// A byte-for-byte repeat of a line already emitted. git
				// resolves it to the same owner either way, so there is
				// nothing to report and nothing lost by emitting it once.
				// Keying on the rendered owners rather than the team name is
				// deliberate: two teams with identical members produce the
				// same file, and the file is what git reads.
				continue
			}
			// Mirrors duplicate-name (internal/catalog/merge.go): anchor on the
			// second entity encountered, name the first's location in the
			// message, and let the first keep the line. The diagnostic is what
			// stops the build.
			c.Add(diag.Diagnostic{
				Severity: diag.SevError,
				Repo:     e.SourceRepo,
				File:     e.SourcePath,
				Line:     e.NameLine,
				Entity:   e.Metadata.Name,
				Check:    "codeowners-duplicate-path",
				Message: fmt.Sprintf(
					"%s is claimed by both %s (%s, %s line %d) and %s (%s), whose teams differ, "+
						"so CODEOWNERS would silently give one of them no review rights",
					e.Spec.Path, prev.by.Ref(), prev.by.Metadata.Owner, prev.by.Location(),
					prev.by.NameLine, e.Ref(), e.Metadata.Owner),
				Hint: "CODEOWNERS is last-match-wins; give them distinct spec.path values, or one owner",
			})
			continue
		}
		claimed[p] = claim{owners: joined, by: e}
		entries = append(entries, entry{path: p, owners: joined})
	}

	sort.Slice(entries, func(i, j int) bool { return entries[i].path < entries[j].path })

	var b strings.Builder
	b.WriteString(Banner("the owner field of each service.yaml, resolved through teams.yaml"))
	b.WriteString("\n")
	for _, e := range entries {
		fmt.Fprintf(&b, "%s %s\n", e.path, e.owners)
	}
	return emit.File{Path: CodeownersPath, Data: []byte(b.String())}
}

// ownedPath renders spec.path as a CODEOWNERS pattern.
//
// A trailing slash restricts the rule to a directory's contents, which is what
// is wanted whenever spec.path names a directory. spec.path is checked for
// existence but deliberately not for directory-ness (spec §5: a Library may
// name a single file), so a path that looks like a file is emitted bare.
func ownedPath(e *catalog.Entity) string {
	p := e.Spec.Path
	if p == "." {
		// A single-service repository: the rule covers everything.
		return "*"
	}
	if strings.Contains(lastSegment(p), ".") {
		return p
	}
	return p + "/"
}

func lastSegment(p string) string {
	if i := strings.LastIndex(p, "/"); i >= 0 {
		return p[i+1:]
	}
	return p
}

// handles renders team members as host handles, adding the leading @ that
// CODEOWNERS requires when the member is written without one. Both spellings
// appear in real teams.yaml files and neither is wrong.
func handles(members []string) []string {
	out := make([]string, 0, len(members))
	for _, m := range members {
		m = strings.TrimSpace(m)
		if m == "" {
			continue
		}
		if !strings.HasPrefix(m, "@") {
			m = "@" + m
		}
		out = append(out, m)
	}
	return out
}
