package generate

import (
	"testing"

	"github.com/landsraadhq/landsraad/internal/catalog"
	"github.com/landsraadhq/landsraad/internal/config"
	"github.com/landsraadhq/landsraad/internal/diag"
)

// ent builds an entity the way the catalog would after parsing.
func ent(name string, kind catalog.Kind, owner, path string) *catalog.Entity {
	e := &catalog.Entity{APIVersion: catalog.APIVersion, Kind: kind}
	e.Metadata.Name = name
	e.Metadata.Owner = owner
	e.Metadata.Tier = 2
	e.Spec.Path = path
	e.SourcePath = path + "/service.yaml"
	e.NameLine = 4
	return e
}

func teamsFrom(t *testing.T, yaml string) *config.Teams {
	t.Helper()
	var c diag.Collector
	teams := config.LoadTeams("teams.yaml", []byte(yaml), &c)
	if c.HasErrors() {
		t.Fatalf("fixture teams.yaml must load: %+v", c.Diagnostics())
	}
	return teams
}

const twoTeams = `teams:
  - name: team-payments
    members: [alice, "@bob"]
    slack: "#payments"
    pagerduty: PAY
  - name: team-sre
    members: [carol]
    slack: "#sre"
    pagerduty: SRE
`

func TestCODEOWNERSRendersOneLinePerEntity(t *testing.T) {
	var c diag.Collector
	cat := catalog.NewCatalog([]*catalog.Entity{
		ent("api", catalog.KindService, "team-payments", "services/api"),
		ent("worker", catalog.KindWorker, "team-sre", "workers/worker"),
	}, &c)

	f := CODEOWNERS(cat, teamsFrom(t, twoTeams), &c)

	if c.HasErrors() {
		t.Fatalf("a complete catalog must generate cleanly: %+v", c.Diagnostics())
	}
	if f.Path != CodeownersPath {
		t.Errorf("Path = %q, want %q", f.Path, CodeownersPath)
	}
	want := `# Generated by landsraad. Do not edit.
# Source: the owner field of each service.yaml, resolved through teams.yaml.
# Run ` + "`landsraad gen`" + ` to regenerate; ` + "`landsraad gen --check`" + ` fails when this is stale.

services/api/ @alice @bob
workers/worker/ @carol
`
	if string(f.Data) != want {
		t.Errorf("CODEOWNERS\n got:\n%s\nwant:\n%s", f.Data, want)
	}
}

// git evaluates CODEOWNERS last-match-wins, so a more specific path must come
// after the general one it overrides. Lexical order gives that, and it also
// makes the file stable between runs — a generated file that reorders itself
// makes --check fail at random.
func TestCODEOWNERSIsSortedByPath(t *testing.T) {
	var c diag.Collector
	cat := catalog.NewCatalog([]*catalog.Entity{
		ent("z", catalog.KindService, "team-sre", "services/z"),
		ent("a", catalog.KindService, "team-payments", "services/a"),
	}, &c)

	f := CODEOWNERS(cat, teamsFrom(t, twoTeams), &c)

	want := "services/a/ @alice @bob\nservices/z/ @carol\n"
	got := string(f.Data)
	if len(got) < len(want) || got[len(got)-len(want):] != want {
		t.Errorf("entries must be sorted by path, got:\n%s", got)
	}
}

// An entity that describes something outside this repository — an externally
// managed Database, a third-party API — omits spec.path (spec §5). Emitting a
// rule for a path that does not exist would be an ownership line git silently
// ignores.
func TestCODEOWNERSSkipsEntitiesWithNoPath(t *testing.T) {
	var c diag.Collector
	cat := catalog.NewCatalog([]*catalog.Entity{
		ent("api", catalog.KindService, "team-payments", "services/api"),
		ent("rds", catalog.KindDatabase, "team-sre", ""),
	}, &c)

	f := CODEOWNERS(cat, teamsFrom(t, twoTeams), &c)

	want := "services/api/ @alice @bob\n"
	got := string(f.Data)
	if got[len(got)-len(want):] != want {
		t.Errorf("expected exactly one entry, got:\n%s", got)
	}
	if c.HasErrors() {
		t.Errorf("an entity without a path is not an error: %+v", c.Diagnostics())
	}
}

// A team with no members produces no owners, and a CODEOWNERS line with a path
// and no owner means "nobody owns this" to git — which silently removes the
// review requirement the file exists to create. Say so instead.
func TestCODEOWNERSReportsATeamWithNoMembers(t *testing.T) {
	var c diag.Collector
	cat := catalog.NewCatalog([]*catalog.Entity{
		ent("api", catalog.KindService, "team-empty", "services/api"),
	}, &c)
	teams := teamsFrom(t, "teams:\n  - name: team-empty\n    slack: \"#e\"\n")

	CODEOWNERS(cat, teams, &c)

	if !c.HasErrors() {
		t.Fatal("a team with no members cannot own anything; that must be an error")
	}
	d := c.Diagnostics()[0]
	if d.Check != "codeowners-no-members" {
		t.Errorf("Check = %q, want %q", d.Check, "codeowners-no-members")
	}
	if d.Line != 4 {
		t.Errorf("Line = %d, want 4 — the entity's name line", d.Line)
	}
	want := `team "team-empty" owns service:api but lists no members, so CODEOWNERS would leave it unowned`
	if d.Message != want {
		t.Errorf("Message\n got: %s\nwant: %s", d.Message, want)
	}
	wantHint := "add members to team-empty in teams.yaml"
	if d.Hint != wantHint {
		t.Errorf("Hint\n got: %s\nwant: %s", d.Hint, wantHint)
	}
}

// An owner that is not in teams.yaml is already an error from validate's
// unknown-owner check. Generating a line naming a team that does not exist
// would put a broken rule in the repository, so it is skipped and reported —
// two diagnostics for one cause is noise, but a silently wrong artifact is
// worse, and the checks run in different commands.
func TestCODEOWNERSReportsAnUnknownOwner(t *testing.T) {
	var c diag.Collector
	cat := catalog.NewCatalog([]*catalog.Entity{
		ent("api", catalog.KindService, "team-nope", "services/api"),
	}, &c)

	CODEOWNERS(cat, teamsFrom(t, twoTeams), &c)

	if !c.HasErrors() {
		t.Fatal("an owner missing from teams.yaml must be an error")
	}
	d := c.Diagnostics()[0]
	if d.Check != "codeowners-unknown-owner" {
		t.Errorf("Check = %q, want %q", d.Check, "codeowners-unknown-owner")
	}
	want := `owner "team-nope" of service:api is not defined in teams.yaml`
	if d.Message != want {
		t.Errorf("Message\n got: %s\nwant: %s", d.Message, want)
	}
}

// The banner is what tells a human who opens the file not to edit it, and
// tells them the command that regenerates it.
func TestBannerNamesTheCommandThatRegenerates(t *testing.T) {
	want := "# Generated by landsraad. Do not edit.\n" +
		"# Source: the owner field of each service.yaml, resolved through teams.yaml.\n" +
		"# Run `landsraad gen` to regenerate; `landsraad gen --check` fails when this is stale.\n"
	if got := Banner("the owner field of each service.yaml, resolved through teams.yaml"); got != want {
		t.Errorf("Banner\n got:\n%s\nwant:\n%s", got, want)
	}
}
