package generate

import (
	"testing"

	"github.com/landsraadhq/landsraad/internal/catalog"
	"github.com/landsraadhq/landsraad/internal/config"
	"github.com/landsraadhq/landsraad/internal/diag"
)

// ent builds an entity the way the catalog would after parsing.
func ent(name string, kind catalog.Kind, owner, path string) *catalog.Entity {
	e := &catalog.Entity{APIVersion: catalog.APIVersion, Kind: kind}
	e.Metadata.Name = name
	e.Metadata.Owner = owner
	e.Metadata.Tier = 2
	e.Spec.Path = path
	e.SourcePath = path + "/service.yaml"
	e.NameLine = 4
	return e
}

func teamsFrom(t *testing.T, yaml string) *config.Teams {
	t.Helper()
	var c diag.Collector
	teams := config.LoadTeams("teams.yaml", []byte(yaml), &c)
	if c.HasErrors() {
		t.Fatalf("fixture teams.yaml must load: %+v", c.Diagnostics())
	}
	return teams
}

const twoTeams = `teams:
  - name: team-payments
    members: [alice, "@bob"]
    slack: "#payments"
    pagerduty: PAY
  - name: team-sre
    members: [carol]
    slack: "#sre"
    pagerduty: SRE
`

func TestCODEOWNERSRendersOneLinePerEntity(t *testing.T) {
	var c diag.Collector
	cat := catalog.NewCatalog([]*catalog.Entity{
		ent("api", catalog.KindService, "team-payments", "services/api"),
		ent("worker", catalog.KindWorker, "team-sre", "workers/worker"),
	}, &c)

	f := CODEOWNERS(cat, teamsFrom(t, twoTeams), &c)

	if c.HasErrors() {
		t.Fatalf("a complete catalog must generate cleanly: %+v", c.Diagnostics())
	}
	if f.Path != CodeownersPath {
		t.Errorf("Path = %q, want %q", f.Path, CodeownersPath)
	}
	want := `# Generated by landsraad. Do not edit.
# Source: the owner field of each service.yaml, resolved through teams.yaml.
# Run ` + "`landsraad gen`" + ` to regenerate; ` + "`landsraad gen --check`" + ` fails when this is stale.

services/api/ @alice @bob
workers/worker/ @carol
`
	if string(f.Data) != want {
		t.Errorf("CODEOWNERS\n got:\n%s\nwant:\n%s", f.Data, want)
	}
}

// git evaluates CODEOWNERS last-match-wins, so a more specific path must come
// after the general one it overrides. Lexical order gives that, and it also
// makes the file stable between runs — a generated file that reorders itself
// makes --check fail at random.
func TestCODEOWNERSIsSortedByPath(t *testing.T) {
	var c diag.Collector
	cat := catalog.NewCatalog([]*catalog.Entity{
		ent("z", catalog.KindService, "team-sre", "services/z"),
		ent("a", catalog.KindService, "team-payments", "services/a"),
	}, &c)

	f := CODEOWNERS(cat, teamsFrom(t, twoTeams), &c)

	want := "services/a/ @alice @bob\nservices/z/ @carol\n"
	got := string(f.Data)
	if len(got) < len(want) || got[len(got)-len(want):] != want {
		t.Errorf("entries must be sorted by path, got:\n%s", got)
	}
}

// An entity that describes something outside this repository — an externally
// managed Database, a third-party API — omits spec.path (spec §5). Emitting a
// rule for a path that does not exist would be an ownership line git silently
// ignores.
func TestCODEOWNERSSkipsEntitiesWithNoPath(t *testing.T) {
	var c diag.Collector
	cat := catalog.NewCatalog([]*catalog.Entity{
		ent("api", catalog.KindService, "team-payments", "services/api"),
		ent("rds", catalog.KindDatabase, "team-sre", ""),
	}, &c)

	f := CODEOWNERS(cat, teamsFrom(t, twoTeams), &c)

	want := "services/api/ @alice @bob\n"
	got := string(f.Data)
	if got[len(got)-len(want):] != want {
		t.Errorf("expected exactly one entry, got:\n%s", got)
	}
	if c.HasErrors() {
		t.Errorf("an entity without a path is not an error: %+v", c.Diagnostics())
	}
}

// A team with no members produces no owners, and a CODEOWNERS line with a path
// and no owner means "nobody owns this" to git — which silently removes the
// review requirement the file exists to create. Say so instead.
func TestCODEOWNERSReportsATeamWithNoMembers(t *testing.T) {
	var c diag.Collector
	cat := catalog.NewCatalog([]*catalog.Entity{
		ent("api", catalog.KindService, "team-empty", "services/api"),
	}, &c)
	teams := teamsFrom(t, "teams:\n  - name: team-empty\n    slack: \"#e\"\n")

	CODEOWNERS(cat, teams, &c)

	if !c.HasErrors() {
		t.Fatal("a team with no members cannot own anything; that must be an error")
	}
	d := c.Diagnostics()[0]
	if d.Check != "codeowners-no-members" {
		t.Errorf("Check = %q, want %q", d.Check, "codeowners-no-members")
	}
	if d.Line != 4 {
		t.Errorf("Line = %d, want 4 — the entity's name line", d.Line)
	}
	want := `team "team-empty" owns service:api but lists no members, so CODEOWNERS would leave it unowned`
	if d.Message != want {
		t.Errorf("Message\n got: %s\nwant: %s", d.Message, want)
	}
	wantHint := "add members to team-empty in teams.yaml"
	if d.Hint != wantHint {
		t.Errorf("Hint\n got: %s\nwant: %s", d.Hint, wantHint)
	}
}

// An owner that is not in teams.yaml is already an error from validate's
// unknown-owner check. Generating a line naming a team that does not exist
// would put a broken rule in the repository, so it is skipped and reported —
// two diagnostics for one cause is noise, but a silently wrong artifact is
// worse, and the checks run in different commands.
func TestCODEOWNERSReportsAnUnknownOwner(t *testing.T) {
	var c diag.Collector
	cat := catalog.NewCatalog([]*catalog.Entity{
		ent("api", catalog.KindService, "team-nope", "services/api"),
	}, &c)

	CODEOWNERS(cat, teamsFrom(t, twoTeams), &c)

	if !c.HasErrors() {
		t.Fatal("an owner missing from teams.yaml must be an error")
	}
	d := c.Diagnostics()[0]
	if d.Check != "codeowners-unknown-owner" {
		t.Errorf("Check = %q, want %q", d.Check, "codeowners-unknown-owner")
	}
	want := `owner "team-nope" of service:api is not defined in teams.yaml`
	if d.Message != want {
		t.Errorf("Message\n got: %s\nwant: %s", d.Message, want)
	}
}

// The banner is what tells a human who opens the file not to edit it, and
// tells them the command that regenerates it.
func TestBannerNamesTheCommandThatRegenerates(t *testing.T) {
	want := "# Generated by landsraad. Do not edit.\n" +
		"# Source: the owner field of each service.yaml, resolved through teams.yaml.\n" +
		"# Run `landsraad gen` to regenerate; `landsraad gen --check` fails when this is stale.\n"
	if got := Banner("the owner field of each service.yaml, resolved through teams.yaml"); got != want {
		t.Errorf("Banner\n got:\n%s\nwant:\n%s", got, want)
	}
}

// entIn is ent for the case R50 is about: two entities that live in different
// service.yaml files but name the same spec.path. ent derives SourcePath from
// the path, which cannot express that shape.
func entIn(name string, kind catalog.Kind, owner, path, source string) *catalog.Entity {
	e := ent(name, kind, owner, path)
	e.SourcePath = source
	return e
}

// Ruling R50. The catalog's uniqueness invariant is (kind, name), so
// service:api and worker:api legally coexist. CODEOWNERS is keyed on path
// instead, and nothing constrains spec.path to be unique — so the projection
// from entities to paths is not injective and the generator assumed it was.
//
// git evaluates CODEOWNERS last-match-wins, so emitting both lines gives one
// of these two teams no review rights at all on a directory this catalog
// records it as owning. That is the "silent corruption instead of a hard
// failure" case the project forbids.
//
// This asserts the complete diagnostic list, not a named subset: the defect
// being fixed is a diagnostic that should have existed and did not, which a
// subset assertion is structurally incapable of detecting.
func TestCODEOWNERSReportsTwoEntitiesClaimingOnePath(t *testing.T) {
	var c diag.Collector
	cat := catalog.NewCatalog([]*catalog.Entity{
		entIn("api", catalog.KindService, "team-payments", "services/api", "services/api/service.yaml"),
		entIn("api", catalog.KindWorker, "team-sre", "services/api", "workers/api/service.yaml"),
	}, &c)

	f := CODEOWNERS(cat, teamsFrom(t, twoTeams), &c)

	diags := c.Diagnostics()
	if len(diags) != 1 {
		t.Fatalf("want exactly 1 diagnostic, got %d: %+v", len(diags), diags)
	}
	d := diags[0]
	if d.Severity != diag.SevError {
		t.Errorf("Severity = %v, want error", d.Severity)
	}
	if d.Check != "codeowners-duplicate-path" {
		t.Errorf("Check = %q, want %q", d.Check, "codeowners-duplicate-path")
	}
	// Mirrors duplicate-name (internal/catalog/merge.go): the diagnostic
	// anchors on the second entity encountered and names the first's location
	// in the message, so both sides are reachable from one line of output.
	if d.File != "workers/api/service.yaml" {
		t.Errorf("File = %q, want the second entity's file", d.File)
	}
	if d.Line != 4 {
		t.Errorf("Line = %d, want 4 — the entity's name line", d.Line)
	}
	want := `services/api is claimed by both service:api (team-payments, services/api/service.yaml line 4) ` +
		`and worker:api (team-sre), whose teams differ, so CODEOWNERS would silently give one of them no review rights`
	if d.Message != want {
		t.Errorf("Message\n got: %s\nwant: %s", d.Message, want)
	}
	wantHint := "CODEOWNERS is last-match-wins; give them distinct spec.path values, or one owner"
	if d.Hint != wantHint {
		t.Errorf("Hint\n got: %s\nwant: %s", d.Hint, wantHint)
	}
	// The first entity still wins the line, as duplicate-name lets the first
	// entity win the index slot. The diagnostic is what stops the build.
	wantLine := "services/api/ @alice @bob\n"
	got := string(f.Data)
	if got[len(got)-len(wantLine):] != wantLine {
		t.Errorf("want exactly one rule for the contested path, got:\n%s", got)
	}
}

// Ruling R50, the other half. Two entities on one path whose owners render
// identically would emit the same line twice. git resolves that to the same
// owner either way, so nothing is lost and there is nothing to report — the
// second line is deduped in silence.
//
// The key is the rendered owners string, not the team name: these are two
// distinct teams with identical members, and the file git reads is the same
// file whichever team is named.
func TestCODEOWNERSDedupsOnePathWhenTheOwnersRenderIdentically(t *testing.T) {
	var c diag.Collector
	cat := catalog.NewCatalog([]*catalog.Entity{
		entIn("api", catalog.KindService, "team-one", "services/api", "services/api/service.yaml"),
		entIn("api", catalog.KindWorker, "team-two", "services/api", "workers/api/service.yaml"),
	}, &c)
	sameMembers := `teams:
  - name: team-one
    members: [alice]
    slack: "#one"
    pagerduty: ONE
  - name: team-two
    members: [alice]
    slack: "#two"
    pagerduty: TWO
`

	f := CODEOWNERS(cat, teamsFrom(t, sameMembers), &c)

	if diags := c.Diagnostics(); len(diags) != 0 {
		t.Fatalf("identical owners lose nothing, so there is nothing to report; got %+v", diags)
	}
	want := `# Generated by landsraad. Do not edit.
# Source: the owner field of each service.yaml, resolved through teams.yaml.
# Run ` + "`landsraad gen`" + ` to regenerate; ` + "`landsraad gen --check`" + ` fails when this is stale.

services/api/ @alice
`
	if string(f.Data) != want {
		t.Errorf("CODEOWNERS\n got:\n%s\nwant:\n%s", f.Data, want)
	}
}
