package generate

import (
	"testing"

	"github.com/landsraadhq/landsraad/internal/catalog"
	"github.com/landsraadhq/landsraad/internal/diag"
)

func TestAlertRoutesEmitsOneReceiverPerOwningTeam(t *testing.T) {
	var c diag.Collector
	cat := catalog.NewCatalog([]*catalog.Entity{
		ent("api", catalog.KindService, "team-payments", "services/api"),
		ent("ledger", catalog.KindService, "team-payments", "services/ledger"),
		ent("worker", catalog.KindWorker, "team-sre", "workers/worker"),
	}, &c)

	f := AlertRoutes(cat, teamsFrom(t, twoTeams), &c)

	if f.Path != AlertRoutesPath {
		t.Errorf("Path = %q, want %q", f.Path, AlertRoutesPath)
	}
	want := Banner("the owner field of each service.yaml, resolved through teams.yaml") + `apiVersion: landsraad/v1
kind: AlertRouting
spec:
  routes:
    - match:
        team: team-payments
      receiver: pagerduty-team-payments
    - match:
        team: team-sre
      receiver: pagerduty-team-sre
  receivers:
    - name: pagerduty-team-payments
      pagerduty_configs:
        - service_key: PAY
    - name: pagerduty-team-sre
      pagerduty_configs:
        - service_key: SRE
`
	if string(f.Data) != want {
		t.Errorf("AlertRoutes\n got:\n%s\nwant:\n%s", f.Data, want)
	}
}

// A team that owns nothing gets no receiver. A receiver nothing routes to is
// dead config, and Alertmanager will not tell anyone it is there.
func TestAlertRoutesOmitsTeamsThatOwnNothing(t *testing.T) {
	var c diag.Collector
	cat := catalog.NewCatalog([]*catalog.Entity{
		ent("api", catalog.KindService, "team-payments", "services/api"),
	}, &c)

	f := AlertRoutes(cat, teamsFrom(t, twoTeams), &c)

	for _, line := range []string{"team-sre", "SRE"} {
		if contains(string(f.Data), line) {
			t.Errorf("team-sre owns nothing and must not appear:\n%s", f.Data)
		}
	}
}

// A team with no PagerDuty key cannot page anyone. Emitting a receiver with an
// empty service_key produces an Alertmanager config that loads fine and pages
// nobody — the failure this whole product exists to prevent, generated by the
// product itself.
func TestAlertRoutesReportsATeamWithNoPagerDuty(t *testing.T) {
	var c diag.Collector
	cat := catalog.NewCatalog([]*catalog.Entity{
		ent("api", catalog.KindService, "team-nopd", "services/api"),
	}, &c)
	teams := teamsFrom(t, "teams:\n  - name: team-nopd\n    members: [a]\n    slack: \"#x\"\n")

	AlertRoutes(cat, teams, &c)

	if !c.HasErrors() {
		t.Fatal("a team that owns something but has no pagerduty key must be an error")
	}
	d := c.Diagnostics()[0]
	if d.Check != "routing-no-pagerduty" {
		t.Errorf("Check = %q, want %q", d.Check, "routing-no-pagerduty")
	}
	if d.File != "teams.yaml" {
		t.Errorf("File = %q, want %q — the file the fix goes in", d.File, "teams.yaml")
	}
	want := `team "team-nopd" owns 1 entity but has no pagerduty key, so its alerts would page nobody`
	if d.Message != want {
		t.Errorf("Message\n got: %s\nwant: %s", d.Message, want)
	}
	wantHint := "add `pagerduty: <service key>` to team-nopd in teams.yaml"
	if d.Hint != wantHint {
		t.Errorf("Hint\n got: %s\nwant: %s", d.Hint, wantHint)
	}
}

func TestSlackMapIsKeyedOnTheRef(t *testing.T) {
	var c diag.Collector
	cat := catalog.NewCatalog([]*catalog.Entity{
		ent("orders", catalog.KindService, "team-payments", "services/orders"),
		ent("orders", catalog.KindTopic, "team-sre", "topics/orders"),
	}, &c)

	f := SlackMap(cat, teamsFrom(t, twoTeams), &c)

	if f.Path != SlackMapPath {
		t.Errorf("Path = %q, want %q", f.Path, SlackMapPath)
	}
	want := Banner("the owner field of each service.yaml, resolved through teams.yaml") + `apiVersion: landsraad/v1
kind: SlackChannels
spec:
  channels:
    service:orders: "#payments"
    topic:orders: "#sre"
`
	if string(f.Data) != want {
		t.Errorf("SlackMap\n got:\n%s\nwant:\n%s", f.Data, want)
	}
}

// The two entities above share the bare name "orders". Keying on the name
// would collapse them and route one team's deploys to the other's channel.
func TestSlackMapDoesNotCollapseEntitiesSharingAName(t *testing.T) {
	var c diag.Collector
	cat := catalog.NewCatalog([]*catalog.Entity{
		ent("orders", catalog.KindService, "team-payments", "services/orders"),
		ent("orders", catalog.KindTopic, "team-sre", "topics/orders"),
	}, &c)

	f := SlackMap(cat, teamsFrom(t, twoTeams), &c)

	if !contains(string(f.Data), "service:orders") || !contains(string(f.Data), "topic:orders") {
		t.Errorf("both refs must appear:\n%s", f.Data)
	}
}

func TestSlackMapReportsATeamWithNoChannel(t *testing.T) {
	var c diag.Collector
	cat := catalog.NewCatalog([]*catalog.Entity{
		ent("api", catalog.KindService, "team-noslack", "services/api"),
	}, &c)
	teams := teamsFrom(t, "teams:\n  - name: team-noslack\n    members: [a]\n    pagerduty: X\n")

	SlackMap(cat, teams, &c)

	if !c.HasErrors() {
		t.Fatal("a team that owns something but has no slack channel must be an error")
	}
	d := c.Diagnostics()[0]
	if d.Check != "routing-no-slack" {
		t.Errorf("Check = %q, want %q", d.Check, "routing-no-slack")
	}
	want := `team "team-noslack" owns 1 entity but has no slack channel, so its deploy notifications would go nowhere`
	if d.Message != want {
		t.Errorf("Message\n got: %s\nwant: %s", d.Message, want)
	}
}

// contains is a local helper: the exact-message rule forbids strings.Contains
// against .Message and .Hint, and this is neither — it inspects generated file
// content, where a substring check is the right tool.
func contains(haystack, needle string) bool {
	return len(haystack) >= len(needle) && indexOf(haystack, needle) >= 0
}

func indexOf(h, n string) int {
	for i := 0; i+len(n) <= len(h); i++ {
		if h[i:i+len(n)] == n {
			return i
		}
	}
	return -1
}
