package generate

import (
	"fmt"
	"sort"
	"strings"

	"github.com/landsraadhq/landsraad/internal/catalog"
	"github.com/landsraadhq/landsraad/internal/config"
	"github.com/landsraadhq/landsraad/internal/diag"
	"github.com/landsraadhq/landsraad/internal/emit"
)

const (
	// AlertRoutesPath is an Alertmanager routing fragment, included from the
	// operator's own alertmanager.yml rather than replacing it: landsraad owns
	// who gets paged, not the rest of the alerting configuration.
	AlertRoutesPath = "alertmanager-routes.yaml"
	// SlackMapPath maps an entity ref to the channel its deploys announce in.
	SlackMapPath = "slack-channels.yaml"
)

// routingSource is the one-line provenance both artifacts carry.
const routingSource = "the owner field of each service.yaml, resolved through teams.yaml"

// owningTeams returns the teams that own at least one entity, sorted by name,
// with the number of entities each owns.
//
// An entity whose owner is not in teams.yaml is skipped without a diagnostic:
// CODEOWNERS already reported codeowners-unknown-owner for that same entity in
// the same run, and three diagnostics for one typo is noise. The asymmetry with
// CODEOWNERS is deliberate — one artifact reports the problem, the rest stay
// quiet about it.
func owningTeams(cat *catalog.Catalog, teams *config.Teams) ([]*config.Team, map[string]int) {
	counts := map[string]int{}
	for _, e := range cat.Entities() {
		if _, ok := teams.Get(e.Metadata.Owner); !ok {
			continue
		}
		counts[e.Metadata.Owner]++
	}
	names := make([]string, 0, len(counts))
	for n := range counts {
		names = append(names, n)
	}
	sort.Strings(names)

	out := make([]*config.Team, 0, len(names))
	for _, n := range names {
		team, _ := teams.Get(n)
		out = append(out, team)
	}
	return out, counts
}

// AlertRoutes renders Alertmanager routes and receivers for every team that
// owns something.
//
// Routes match on a `team` label rather than on a service name, which is what
// keeps this file stable as services are added: a new service owned by an
// existing team changes nothing here. It is the alerting rules' job to attach
// that label, and spec.alerts is where those rules live.
func AlertRoutes(cat *catalog.Catalog, teams *config.Teams, c *diag.Collector) emit.File {
	owners, counts := owningTeams(cat, teams)

	var b strings.Builder
	b.WriteString(Banner(routingSource))
	b.WriteString("apiVersion: landsraad/v1\n")
	b.WriteString("kind: AlertRouting\n")
	b.WriteString("spec:\n")

	b.WriteString("  routes:\n")
	for _, team := range owners {
		if team.PagerDuty == "" {
			// A receiver with an empty service_key loads without complaint and
			// pages nobody. That is the failure this product exists to
			// prevent, generated by the product itself.
			c.Add(diag.Diagnostic{
				Severity: diag.SevError,
				File:     "teams.yaml",
				Line:     1,
				Check:    "routing-no-pagerduty",
				Message: fmt.Sprintf("team %q owns %s but has no pagerduty key, so its alerts would page nobody",
					team.Name, plural(counts[team.Name], "entity", "entities")),
				Hint: fmt.Sprintf("add `pagerduty: <service key>` to %s in teams.yaml", team.Name),
			})
			continue
		}
		fmt.Fprintf(&b, "    - match:\n        team: %s\n      receiver: pagerduty-%s\n", team.Name, team.Name)
	}

	b.WriteString("  receivers:\n")
	for _, team := range owners {
		if team.PagerDuty == "" {
			continue
		}
		fmt.Fprintf(&b, "    - name: pagerduty-%s\n      pagerduty_configs:\n        - service_key: %s\n",
			team.Name, team.PagerDuty)
	}

	return emit.File{Path: AlertRoutesPath, Data: []byte(b.String())}
}

// SlackMap renders ref → channel for every entity with a resolvable owner.
//
// Keyed on the ref, never the bare name (spec §12): service:orders and
// topic:orders are distinct entities that may coexist, and a deploy pipeline
// looking up "orders" would get one team's channel for the other's deploy.
func SlackMap(cat *catalog.Catalog, teams *config.Teams, c *diag.Collector) emit.File {
	_, counts := owningTeams(cat, teams)

	type line struct{ ref, channel string }
	var lines []line
	reported := map[string]bool{}

	for _, e := range cat.Entities() {
		team, ok := teams.Get(e.Metadata.Owner)
		if !ok {
			continue
		}
		if team.Slack == "" {
			// Reported once per team, not once per entity: a team owning
			// twelve services should produce one diagnostic, not twelve.
			if !reported[team.Name] {
				reported[team.Name] = true
				c.Add(diag.Diagnostic{
					Severity: diag.SevError,
					File:     "teams.yaml",
					Line:     1,
					Check:    "routing-no-slack",
					Message: fmt.Sprintf("team %q owns %s but has no slack channel, so its deploy notifications would go nowhere",
						team.Name, plural(counts[team.Name], "entity", "entities")),
					Hint: fmt.Sprintf("add `slack: \"#channel\"` to %s in teams.yaml", team.Name),
				})
			}
			continue
		}
		lines = append(lines, line{ref: e.Ref().String(), channel: team.Slack})
	}

	sort.Slice(lines, func(i, j int) bool { return lines[i].ref < lines[j].ref })

	var b strings.Builder
	b.WriteString(Banner(routingSource))
	b.WriteString("apiVersion: landsraad/v1\n")
	b.WriteString("kind: SlackChannels\n")
	b.WriteString("spec:\n")
	b.WriteString("  channels:\n")
	for _, l := range lines {
		// Quoted because a channel begins with '#', which YAML would otherwise
		// read as a comment.
		fmt.Fprintf(&b, "    %s: %q\n", l.ref, l.channel)
	}
	return emit.File{Path: SlackMapPath, Data: []byte(b.String())}
}

// plural renders a count with the right noun, as cmd/landsraad does for the
// validate summary. "1 entities" in a diagnostic is the same defect as "1
// entities validated" on stdout.
func plural(n int, one, many string) string {
	if n == 1 {
		return fmt.Sprintf("%d %s", n, one)
	}
	return fmt.Sprintf("%d %s", n, many)
}
